In [ ]:
import numpy as np
import pandas as pd
import sys

In [ ]:
# Activation function
def activation(net):
  return 2 / (1 + np.exp(-1*net)) - 1

In [ ]:
def deltaRule(input_vector, target):
  # Initialization
  lr = 0.1
  weight = (1, -1, 0, 0.5)
  w1, w2, w3, w4 = weight
  print("Learning Rate =", lr)
  print("Initial weights:\nw1 = {0}\t\tw2 = {1}\t\tw3 = {2}\t\tw4 = {3}".format(w1, w2, w3, w4))

  # Delta Learning Rule
  result = [0, 0, 0, 0]
  j = 0
  old_error = sys.maxsize

  while True:
    j += 1
    print("\nEpoch {0}:".format(j))
    i = 0
    for input in input_vector:
        x1, x2, x3, x4 = input
        t = target[i]
        net = round(x1*w1 + x2*w2 + x3*w3 + x4*w4, 3)
        result[i] = net
        y = round(activation(net), 3)
        grad_y = round(0.5 * (1 - y**2), 3)
        # print("net = {0}\no = {1}\nf'(net) = {2}".format(net, y, grad_y))
        w1 = round(w1 + lr * (t-y) * grad_y * x1, 3)
        w2 = round(w2 + lr * (t-y) * grad_y * x2, 3)
        w3 = round(w3 + lr * (t-y) * grad_y * x3, 3)
        w4 = round(w4 + lr * (t-y) * grad_y * x4, 3)
        i += 1
        print("Updated weights after input {0}:\nw1 = {1}\tw2 = {2}\tw3 = {3}\tw4 = {4}".format(i, w1, w2, w3, w4))

    # Error calculation
    error = 0
    for i in range(len(input_vector)):
      error += 1/2*(target[i] - result[i])**2
    print("Error =", error)

    if error > old_error:
      break

    old_weights = w1, w2, w3, w4
    old_error = error

  fw1, fw2, fw3, fw4 = old_weights
  print("\nFinal weights for minimum error:\nw1 = {1}\tw2 = {2}\tw3 = {3}\tw4 = {4}".format(i, fw1, fw2, fw3, fw4))

  return old_weights

In [ ]:
def test(input_vector, weights):
  predict = [0] * len(input_vector)
  w1, w2, w3, w4 = weights
  i = 0
  for input in input_vector:
    x1, x2, x3, x4 = input
    net = round(x1*w1 + x2*w2 + x3*w3 + x4*w4, 3)
    y = round(activation(net), 3)
    predict[i] = y
    i += 1
  return predict

In [ ]:
def displayTable(input_vector, target, prediction):
  column_names = pd.DataFrame([["Input", "x1"],
                              ["Input", "x2"],
                              ["Input", "x3"],
                              ["Input", "x4"],
                              ["Target", "t"],
                              ["Predicted", ""],
                              ["Sign", ""],
                              ["Class", ""]],
                              columns=["", ""])

  rows = []
  for i, input in enumerate(input_vector):
    row = []
    x1, x2, x3, x4 = input
    if prediction[i] > 0:
      sign = '+'
      class_no = 1
    else:
      sign = '-'
      class_no = 2
    row.extend([x1, x2, x3, x4, target[i], prediction[i], sign, class_no])
    rows.append(row)

  columns = pd.MultiIndex.from_frame(column_names)

  df = pd.DataFrame(rows, columns=columns)
  pd.set_option('display.precision', 3)
  display(df)
  return

In [ ]:
x_1 = [1, -2, 0, -1]
x_2 = [0, 1.5, -0.5, -1]
x_3 = [-1, 1, 0.5, -1]
input_vector = []
input_vector.extend([x_1, x_2, x_3])
target = [-1, -1, 1]
min_error = 1.5
weights = deltaRule(input_vector, target)
prediction = test(input_vector, weights)
displayTable(input_vector, target, prediction)

Learning Rate = 0.1
Initial weights:
w1 = 1		w2 = -1		w3 = 0		w4 = 0.5

Epoch 1:
Updated weights after input 1:
w1 = 0.974	w2 = -0.948	w3 = 0.0	w4 = 0.526
Updated weights after input 2:
w1 = 0.974	w2 = -0.956	w3 = 0.003	w4 = 0.531
Updated weights after input 3:
w1 = 0.947	w2 = -0.929	w3 = 0.016	w4 = 0.504
Error = 12.560152

Epoch 2:
Updated weights after input 1:
w1 = 0.917	w2 = -0.869	w3 = 0.016	w4 = 0.534
Updated weights after input 2:
w1 = 0.917	w2 = -0.879	w3 = 0.019	w4 = 0.54
Updated weights after input 3:
w1 = 0.887	w2 = -0.849	w3 = 0.034	w4 = 0.51
Error = 11.340623

Epoch 3:
Updated weights after input 1:
w1 = 0.852	w2 = -0.779	w3 = 0.034	w4 = 0.545
Updated weights after input 2:
w1 = 0.852	w2 = -0.791	w3 = 0.038	w4 = 0.553
Updated weights after input 3:
w1 = 0.819	w2 = -0.758	w3 = 0.054	w4 = 0.52
Error = 10.041657500000001

Epoch 4:
Updated weights after input 1:
w1 = 0.778	w2 = -0.675	w3 = 0.054	w4 = 0.561
Updated weights after input 2:
w1 = 0.778	w2 = -0.689	w3 = 0.059	w4 = 0.57
Updated weights after input 3:
w1 = 0.741	w2 = -0.652	w3 = 0.077	w4 = 0.533
Error = 8.6637375

Epoch 5:
Updated weights after input 1:
w1 = 0.692	w2 = -0.555	w3 = 0.077	w4 = 0.582
Updated weights after input 2:
w1 = 0.692	w2 = -0.572	w3 = 0.083	w4 = 0.594
Updated weights after input 3:
w1 = 0.651	w2 = -0.531	w3 = 0.104	w4 = 0.553
Error = 7.222604499999999

Epoch 6:
Updated weights after input 1:
w1 = 0.596	w2 = -0.42	w3 = 0.104	w4 = 0.608
Updated weights after input 2:
w1 = 0.596	w2 = -0.442	w3 = 0.111	w4 = 0.623
Updated weights after input 3:
w1 = 0.55	w2 = -0.396	w3 = 0.134	w4 = 0.577
Error = 5.770468

Epoch 7:
Updated weights after input 1:
w1 = 0.491	w2 = -0.278	w3 = 0.134	w4 = 0.636
Updated weights after input 2:
w1 = 0.491	w2 = -0.305	w3 = 0.143	w4 = 0.654
Updated weights after input 3:
w1 = 0.44	w2 = -0.254	w3 = 0.169	w4 = 0.603
Error = 4.392254500000001

Epoch 8:
Updated weights after input 1:
w1 = 0.383	w2 = -0.14	w3 = 0.169	w4 = 0.66
Updated weights after input 2:
w1 = 0.383	w2 = -0.173	w3 = 0.18	w4 = 0.682
Updated weights after input 3:
w1 = 0.327	w2 = -0.117	w3 = 0.208	w4 = 0.626
Error = 3.2124769999999994

Epoch 9:
Updated weights after input 1:
w1 = 0.279	w2 = -0.02	w3 = 0.208	w4 = 0.674
Updated weights after input 2:
w1 = 0.279	w2 = -0.06	w3 = 0.221	w4 = 0.7
Updated weights after input 3:
w1 = 0.221	w2 = -0.002	w3 = 0.25	w4 = 0.642
Error = 2.3141365

Epoch 10:
Updated weights after input 1:
w1 = 0.183	w2 = 0.074	w3 = 0.25	w4 = 0.68
Updated weights after input 2:
w1 = 0.183	w2 = 0.03	w3 = 0.265	w4 = 0.71
Updated weights after input 3:
w1 = 0.124	w2 = 0.089	w3 = 0.295	w4 = 0.651
Error = 1.7132125

Epoch 11:
Updated weights after input 1:
w1 = 0.095	w2 = 0.148	w3 = 0.295	w4 = 0.68
Updated weights after input 2:
w1 = 0.095	w2 = 0.1	w3 = 0.311	w4 = 0.712
Updated weights after input 3:
w1 = 0.036	w2 = 0.159	w3 = 0.34	w4 = 0.653
Error = 1.3254825000000001

Epoch 12:
Updated weights after input 1:
w1 = 0.013	w2 = 0.205	w3 = 0.34	w4 = 0.676
Updated weights after input 2:
w1 = 0.013	w2 = 0.154	w3 = 0.357	w4 = 0.71
Updated weights after input 3:
w1 = -0.044	w2 = 0.211	w3 = 0.386	w4 = 0.653
Error = 1.0744230000000001

Epoch 13:
Updated weights after input 1:
w1 = -0.062	w2 = 0.248	w3 = 0.386	w4 = 0.671
Updated weights after input 2:
w1 = -0.062	w2 = 0.194	w3 = 0.404	w4 = 0.707
Updated weights after input 3:
w1 = -0.117	w2 = 0.249	w3 = 0.432	w4 = 0.652
Error = 0.9161130000000001

Epoch 14:
Updated weights after input 1:
w1 = -0.132	w2 = 0.279	w3 = 0.432	w4 = 0.667
Updated weights after input 2:
w1 = -0.132	w2 = 0.224	w3 = 0.45	w4 = 0.704
Updated weights after input 3:
w1 = -0.185	w2 = 0.277	w3 = 0.476	w4 = 0.651
Error = 0.8098569999999999

Epoch 15:
Updated weights after input 1:
w1 = -0.198	w2 = 0.302	w3 = 0.476	w4 = 0.664
Updated weights after input 2:
w1 = -0.198	w2 = 0.246	w3 = 0.495	w4 = 0.701
Updated weights after input 3:
w1 = -0.248	w2 = 0.296	w3 = 0.52	w4 = 0.651
Error = 0.7368909999999999

Epoch 16:
Updated weights after input 1:
w1 = -0.259	w2 = 0.318	w3 = 0.52	w4 = 0.662
Updated weights after input 2:
w1 = -0.259	w2 = 0.262	w3 = 0.539	w4 = 0.699
Updated weights after input 3:
w1 = -0.307	w2 = 0.31	w3 = 0.563	w4 = 0.651
Error = 0.6867850000000001

Epoch 17:
Updated weights after input 1:
w1 = -0.317	w2 = 0.329	w3 = 0.563	w4 = 0.661
Updated weights after input 2:
w1 = -0.317	w2 = 0.273	w3 = 0.582	w4 = 0.698
Updated weights after input 3:
w1 = -0.362	w2 = 0.318	w3 = 0.605	w4 = 0.653
Error = 0.652587

Epoch 18:
Updated weights after input 1:
w1 = -0.371	w2 = 0.335	w3 = 0.605	w4 = 0.662
Updated weights after input 2:
w1 = -0.371	w2 = 0.28	w3 = 0.623	w4 = 0.699
Updated weights after input 3:
w1 = -0.414	w2 = 0.323	w3 = 0.644	w4 = 0.656
Error = 0.6274705

Epoch 19:
Updated weights after input 1:
w1 = -0.422	w2 = 0.339	w3 = 0.644	w4 = 0.664
Updated weights after input 2:
w1 = -0.422	w2 = 0.285	w3 = 0.662	w4 = 0.7
Updated weights after input 3:
w1 = -0.462	w2 = 0.325	w3 = 0.682	w4 = 0.66
Error = 0.6116919999999999

Epoch 20:
Updated weights after input 1:
w1 = -0.469	w2 = 0.339	w3 = 0.682	w4 = 0.667
Updated weights after input 2:
w1 = -0.469	w2 = 0.286	w3 = 0.7	w4 = 0.702
Updated weights after input 3:
w1 = -0.507	w2 = 0.324	w3 = 0.719	w4 = 0.664
Error = 0.6011965

Epoch 21:
Updated weights after input 1:
w1 = -0.514	w2 = 0.337	w3 = 0.719	w4 = 0.671
Updated weights after input 2:
w1 = -0.514	w2 = 0.285	w3 = 0.736	w4 = 0.706
Updated weights after input 3:
w1 = -0.551	w2 = 0.322	w3 = 0.754	w4 = 0.669
Error = 0.5934534999999999

Epoch 22:
Updated weights after input 1:
w1 = -0.557	w2 = 0.334	w3 = 0.754	w4 = 0.675
Updated weights after input 2:
w1 = -0.557	w2 = 0.283	w3 = 0.771	w4 = 0.709
Updated weights after input 3:
w1 = -0.592	w2 = 0.318	w3 = 0.788	w4 = 0.674
Error = 0.590693

Epoch 23:
Updated weights after input 1:
w1 = -0.598	w2 = 0.33	w3 = 0.788	w4 = 0.68
Updated weights after input 2:
w1 = -0.598	w2 = 0.28	w3 = 0.805	w4 = 0.713
Updated weights after input 3:
w1 = -0.631	w2 = 0.313	w3 = 0.822	w4 = 0.68
Error = 0.5887345

Epoch 24:
Updated weights after input 1:
w1 = -0.637	w2 = 0.324	w3 = 0.822	w4 = 0.686
Updated weights after input 2:
w1 = -0.637	w2 = 0.276	w3 = 0.838	w4 = 0.718
Updated weights after input 3:
w1 = -0.669	w2 = 0.308	w3 = 0.854	w4 = 0.686
Error = 0.589143

Final weights for minimum error:
w1 = -0.631	w2 = 0.313	w3 = 0.822	w4 = 0.68

  Input              Target Predicted Sign Class
     x1   x2   x3 x4      t
0     1 -2.0  0.0 -1     -1    -0.748    -     2
1     0  1.5 -0.5 -1     -1    -0.301    -     2
2    -1  1.0  0.5 -1      1     0.325    +     1

In [ ]:
x_1 = [1, -1, 1, -1]
x_2 = [1, 1, 1, 1]
x_3 = [1, 1, 1, -1]
x_4 = [1, -1, -1, 1]
input_vector = []
input_vector.extend([x_1, x_2, x_3, x_4])
target = [-1, 1, -1, -1]
weights = deltaRule(input_vector, target)
prediction = test(input_vector, weights)
displayTable(input_vector, target, prediction)

Learning Rate = 0.1
Initial weights:
w1 = 1		w2 = -1		w3 = 0		w4 = 0.5

Epoch 1:
Updated weights after input 1:
w1 = 0.951	w2 = -0.951	w3 = -0.049	w4 = 0.549
Updated weights after input 2:
w1 = 0.986	w2 = -0.916	w3 = -0.014	w4 = 0.584
Updated weights after input 3:
w1 = 0.951	w2 = -0.951	w3 = -0.049	w4 = 0.619
Updated weights after input 4:
w1 = 0.926	w2 = -0.926	w3 = -0.024	w4 = 0.594
Error = 9.733842

Epoch 2:
Updated weights after input 1:
w1 = 0.872	w2 = -0.872	w3 = -0.078	w4 = 0.648
Updated weights after input 2:
w1 = 0.905	w2 = -0.839	w3 = -0.045	w4 = 0.681
Updated weights after input 3:
w1 = 0.874	w2 = -0.87	w3 = -0.076	w4 = 0.712
Updated weights after input 4:
w1 = 0.849	w2 = -0.845	w3 = -0.051	w4 = 0.687
Error = 8.88314

Epoch 3:
Updated weights after input 1:
w1 = 0.791	w2 = -0.787	w3 = -0.109	w4 = 0.745
Updated weights after input 2:
w1 = 0.822	w2 = -0.756	w3 = -0.078	w4 = 0.776
Updated weights after input 3:
w1 = 0.795	w2 = -0.783	w3 = -0.105	w4 = 0.803
Updated weights after input 4:
w1 = 0.769	w2 = -0.757	w3 = -0.079	w4 = 0.777
Error = 8.076338

Epoch 4:
Updated weights after input 1:
w1 = 0.71	w2 = -0.698	w3 = -0.138	w4 = 0.836
Updated weights after input 2:
w1 = 0.739	w2 = -0.669	w3 = -0.109	w4 = 0.865
Updated weights after input 3:
w1 = 0.715	w2 = -0.693	w3 = -0.133	w4 = 0.889
Updated weights after input 4:
w1 = 0.688	w2 = -0.666	w3 = -0.106	w4 = 0.862
Error = 7.323558

Epoch 5:
Updated weights after input 1:
w1 = 0.631	w2 = -0.609	w3 = -0.163	w4 = 0.919
Updated weights after input 2:
w1 = 0.658	w2 = -0.582	w3 = -0.136	w4 = 0.946
Updated weights after input 3:
w1 = 0.637	w2 = -0.603	w3 = -0.157	w4 = 0.967
Updated weights after input 4:
w1 = 0.608	w2 = -0.574	w3 = -0.128	w4 = 0.938
Error = 6.643406

Epoch 6:
Updated weights after input 1:
w1 = 0.555	w2 = -0.521	w3 = -0.181	w4 = 0.991
Updated weights after input 2:
w1 = 0.58	w2 = -0.496	w3 = -0.156	w4 = 1.016
Updated weights after input 3:
w1 = 0.561	w2 = -0.515	w3 = -0.175	w4 = 1.035
Updated weights after input 4:
w1 = 0.531	w2 = -0.485	w3 = -0.145	w4 = 1.005
Error = 6.037666

Epoch 7:
Updated weights after input 1:
w1 = 0.485	w2 = -0.439	w3 = -0.191	w4 = 1.051
Updated weights after input 2:
w1 = 0.509	w2 = -0.415	w3 = -0.167	w4 = 1.075
Updated weights after input 3:
w1 = 0.491	w2 = -0.433	w3 = -0.185	w4 = 1.093
Updated weights after input 4:
w1 = 0.459	w2 = -0.401	w3 = -0.153	w4 = 1.061
Error = 5.51675

Epoch 8:
Updated weights after input 1:
w1 = 0.419	w2 = -0.361	w3 = -0.193	w4 = 1.101
Updated weights after input 2:
w1 = 0.441	w2 = -0.339	w3 = -0.171	w4 = 1.123
Updated weights after input 3:
w1 = 0.424	w2 = -0.356	w3 = -0.188	w4 = 1.14
Updated weights after input 4:
w1 = 0.39	w2 = -0.322	w3 = -0.154	w4 = 1.106
Error = 5.057500000000001

Epoch 9:
Updated weights after input 1:
w1 = 0.356	w2 = -0.288	w3 = -0.188	w4 = 1.14
Updated weights after input 2:
w1 = 0.377	w2 = -0.267	w3 = -0.167	w4 = 1.161
Updated weights after input 3:
w1 = 0.361	w2 = -0.283	w3 = -0.183	w4 = 1.177
Updated weights after input 4:
w1 = 0.324	w2 = -0.246	w3 = -0.146	w4 = 1.14
Error = 4.638122

Epoch 10:
Updated weights after input 1:
w1 = 0.295	w2 = -0.217	w3 = -0.175	w4 = 1.169
Updated weights after input 2:
w1 = 0.314	w2 = -0.198	w3 = -0.156	w4 = 1.188
Updated weights after input 3:
w1 = 0.298	w2 = -0.214	w3 = -0.172	w4 = 1.204
Updated weights after input 4:
w1 = 0.258	w2 = -0.174	w3 = -0.132	w4 = 1.164
Error = 4.239184

Epoch 11:
Updated weights after input 1:
w1 = 0.233	w2 = -0.149	w3 = -0.157	w4 = 1.189
Updated weights after input 2:
w1 = 0.251	w2 = -0.131	w3 = -0.139	w4 = 1.207
Updated weights after input 3:
w1 = 0.235	w2 = -0.147	w3 = -0.155	w4 = 1.223
Updated weights after input 4:
w1 = 0.192	w2 = -0.104	w3 = -0.112	w4 = 1.18
Error = 3.850313999999999

Epoch 12:
Updated weights after input 1:
w1 = 0.171	w2 = -0.083	w3 = -0.133	w4 = 1.201
Updated weights after input 2:
w1 = 0.188	w2 = -0.066	w3 = -0.116	w4 = 1.218
Updated weights after input 3:
w1 = 0.172	w2 = -0.082	w3 = -0.132	w4 = 1.234
Updated weights after input 4:
w1 = 0.126	w2 = -0.036	w3 = -0.086	w4 = 1.188
Error = 3.466848

Epoch 13:
Updated weights after input 1:
w1 = 0.108	w2 = -0.018	w3 = -0.104	w4 = 1.206
Updated weights after input 2:
w1 = 0.125	w2 = -0.001	w3 = -0.087	w4 = 1.223
Updated weights after input 3:
w1 = 0.108	w2 = -0.018	w3 = -0.104	w4 = 1.24
Updated weights after input 4:
w1 = 0.059	w2 = 0.031	w3 = -0.055	w4 = 1.191
Error = 3.0924519999999993

Epoch 14:
Updated weights after input 1:
w1 = 0.043	w2 = 0.047	w3 = -0.071	w4 = 1.207
Updated weights after input 2:
w1 = 0.059	w2 = 0.063	w3 = -0.055	w4 = 1.223
Updated weights after input 3:
w1 = 0.042	w2 = 0.046	w3 = -0.072	w4 = 1.24
Updated weights after input 4:
w1 = -0.011	w2 = 0.099	w3 = -0.019	w4 = 1.187
Error = 2.7249

Epoch 15:
Updated weights after input 1:
w1 = -0.025	w2 = 0.113	w3 = -0.033	w4 = 1.201
Updated weights after input 2:
w1 = -0.01	w2 = 0.128	w3 = -0.018	w4 = 1.216
Updated weights after input 3:
w1 = -0.028	w2 = 0.11	w3 = -0.036	w4 = 1.234
Updated weights after input 4:
w1 = -0.084	w2 = 0.166	w3 = 0.02	w4 = 1.178
Error = 2.3621359999999996

Epoch 16:
Updated weights after input 1:
w1 = -0.096	w2 = 0.178	w3 = 0.008	w4 = 1.19
Updated weights after input 2:
w1 = -0.081	w2 = 0.193	w3 = 0.023	w4 = 1.205
Updated weights after input 3:
w1 = -0.1	w2 = 0.174	w3 = 0.004	w4 = 1.224
Updated weights after input 4:
w1 = -0.158	w2 = 0.232	w3 = 0.062	w4 = 1.166
Error = 2.01834

Epoch 17:
Updated weights after input 1:
w1 = -0.169	w2 = 0.243	w3 = 0.051	w4 = 1.177
Updated weights after input 2:
w1 = -0.155	w2 = 0.257	w3 = 0.065	w4 = 1.191
Updated weights after input 3:
w1 = -0.176	w2 = 0.236	w3 = 0.044	w4 = 1.212
Updated weights after input 4:
w1 = -0.235	w2 = 0.295	w3 = 0.103	w4 = 1.153
Error = 1.709676

Epoch 18:
Updated weights after input 1:
w1 = -0.245	w2 = 0.305	w3 = 0.093	w4 = 1.163
Updated weights after input 2:
w1 = -0.231	w2 = 0.319	w3 = 0.107	w4 = 1.177
Updated weights after input 3:
w1 = -0.253	w2 = 0.297	w3 = 0.085	w4 = 1.199
Updated weights after input 4:
w1 = -0.312	w2 = 0.356	w3 = 0.144	w4 = 1.14
Error = 1.4413380000000002

Epoch 19:
Updated weights after input 1:
w1 = -0.32	w2 = 0.364	w3 = 0.136	w4 = 1.148
Updated weights after input 2:
w1 = -0.306	w2 = 0.378	w3 = 0.15	w4 = 1.162
Updated weights after input 3:
w1 = -0.329	w2 = 0.355	w3 = 0.127	w4 = 1.185
Updated weights after input 4:
w1 = -0.386	w2 = 0.412	w3 = 0.184	w4 = 1.128
Error = 1.2199780000000002

Epoch 20:
Updated weights after input 1:
w1 = -0.394	w2 = 0.42	w3 = 0.176	w4 = 1.136
Updated weights after input 2:
w1 = -0.38	w2 = 0.434	w3 = 0.19	w4 = 1.15
Updated weights after input 3:
w1 = -0.404	w2 = 0.41	w3 = 0.166	w4 = 1.174
Updated weights after input 4:
w1 = -0.458	w2 = 0.464	w3 = 0.22	w4 = 1.12
Error = 1.04964

Epoch 21:
Updated weights after input 1:
w1 = -0.465	w2 = 0.471	w3 = 0.213	w4 = 1.127
Updated weights after input 2:
w1 = -0.451	w2 = 0.485	w3 = 0.227	w4 = 1.141
Updated weights after input 3:
w1 = -0.475	w2 = 0.461	w3 = 0.203	w4 = 1.165
Updated weights after input 4:
w1 = -0.526	w2 = 0.512	w3 = 0.254	w4 = 1.114
Error = 0.931238

Epoch 22:
Updated weights after input 1:
w1 = -0.532	w2 = 0.518	w3 = 0.248	w4 = 1.12
Updated weights after input 2:
w1 = -0.519	w2 = 0.531	w3 = 0.261	w4 = 1.133
Updated weights after input 3:
w1 = -0.544	w2 = 0.506	w3 = 0.236	w4 = 1.158
Updated weights after input 4:
w1 = -0.591	w2 = 0.553	w3 = 0.283	w4 = 1.111
Error = 0.8558519999999998

Epoch 23:
Updated weights after input 1:
w1 = -0.596	w2 = 0.558	w3 = 0.278	w4 = 1.116
Updated weights after input 2:
w1 = -0.583	w2 = 0.571	w3 = 0.291	w4 = 1.129
Updated weights after input 3:
w1 = -0.608	w2 = 0.546	w3 = 0.266	w4 = 1.154
Updated weights after input 4:
w1 = -0.651	w2 = 0.589	w3 = 0.309	w4 = 1.111
Error = 0.816388

Epoch 24:
Updated weights after input 1:
w1 = -0.656	w2 = 0.594	w3 = 0.304	w4 = 1.116
Updated weights after input 2:
w1 = -0.643	w2 = 0.607	w3 = 0.317	w4 = 1.129
Updated weights after input 3:
w1 = -0.668	w2 = 0.582	w3 = 0.292	w4 = 1.154
Updated weights after input 4:
w1 = -0.707	w2 = 0.621	w3 = 0.331	w4 = 1.115
Error = 0.8057879999999998

Epoch 25:
Updated weights after input 1:
w1 = -0.711	w2 = 0.625	w3 = 0.327	w4 = 1.119
Updated weights after input 2:
w1 = -0.698	w2 = 0.638	w3 = 0.34	w4 = 1.132
Updated weights after input 3:
w1 = -0.723	w2 = 0.613	w3 = 0.315	w4 = 1.157
Updated weights after input 4:
w1 = -0.759	w2 = 0.649	w3 = 0.351	w4 = 1.121
Error = 0.8220420000000002

Final weights for minimum error:
w1 = -0.707	w2 = 0.621	w3 = 0.331	w4 = 1.115

  Input          Target Predicted Sign Class
     x1 x2 x3 x4      t
0     1 -1  1 -1     -1    -0.784    -     2
1     1  1  1  1      1     0.592    +     1
2     1  1  1 -1     -1    -0.409    -     2
3     1 -1 -1  1     -1    -0.265    -     2